changes to update

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -31,18 +31,21 @@ jobs:
           sudo reboot
           sleep 600
 
-    - name: Wait for VMs to come back
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.HOST }}
-        username: ${{ secrets.USERNAME }}
-        password: ${{ secrets.PASSWORD }}
-        script: |
-          echo "Running vm to comeback"
-          until ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'exit'; do sleep 1000; done
-          if [ $? -ne 0 ]; then
-            echo "Error: Failed to connect to the VM"
-            exit 1
-          else
-            echo "Success"
-          fi
+  wait-for-vms:
+    runs-on: ubuntu-latest
+    steps:        
+      - name: Wait for VMs to come back
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          password: ${{ secrets.PASSWORD }}
+          script: |
+            echo "Running vm to comeback"
+            until ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'exit'; do sleep 1000; done
+            if [ $? -ne 0 ]; then
+              echo "Error: Failed to connect to the VM"
+              exit 1
+            else
+              echo "Success"
+            fi
